years = int(input("Please enter age in years"))
days = years * 365
hours = days * 24
minutes = hours * 3600
seconds = minutes * 60
print(f'Age in Days is = {days}')
print(f'Age in Hours is = {hours}')
print(f'Age in Minutes is = {minutes}')
print(f'Age in Seconds is = {seconds}')